{{- $env := $.Values.environment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.name }}
  namespace: {{ required "A valid .namespace entry required!" $.Values.namespace }}
  labels:
    {{- include "muscat.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ $.Values.replicaCount }}
  revisionHistoryLimit: 3  
  selector:
    matchLabels:
      {{- include "muscat.selectorLabels" . | nindent 6 }}
  strategy:
    {{- if eq $.Values.strategyType "RollingUpdate" }}
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    {{- end }}
    type: {{ $.Values.strategyType }}
  template:
    metadata:
      labels:
        {{- include "muscat.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ $.Values.name }}
          {{- if eq $env "production" }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default "latest" }}"
          {{- else }}
          image: "{{ $.Values.image.repository }}-{{ $.Values.environment }}:{{ $.Values.image.tag | default "latest" }}"
          {{- end }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: 9090
              name: 80tcp02
              protocol: TCP
          resources:
            limits:
              cpu: {{ $.Values.resources.limits.cpu }}
              memory: {{ $.Values.resources.limits.memory }}        
            requests:
              cpu: {{ $.Values.resources.requests.cpu }}
              memory: {{ $.Values.resources.requests.memory }}
---