# Default values for gitops-argocd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: malvasia-qa
env: default

replicaCount: 1

image:
  repository: csturion/gitops-argocd
  pullPolicy: IfNotPresent
  # Overrides the image tag whose malvasia-qa is the chart appVersion.
  tag: abcdef01

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

